### ISSUE TITLE
Buggy library in list

### ISSUE THREAD

**Issue by sm-g** [heynickc/awesome-ddd#107]
Hi, there is [Value](https://github.com/tpierrain/Value) listed in Libraries and Frameworks section, which is not as good as it seems. 
First, nuget feed of this project is not updating and overall development is stopped. 
Second, it contains some bugs, which makes it not usable.
I had to write my version of helper library for the same purpose ([ByValue](https://github.com/sm-g/ByValue)) with fixed collections comparing support (if you look for replacement in list, would be glad to see it there).

**Comment by heynickc** [comment]
@sm-g feel free to open a PR for ByValue and I'm happy to merge.
