### ISSUE TITLE
Visual Tools?

### ISSUE THREAD

**Issue by inforeqd512** [heynickc/awesome-ddd#29]
Hi, 

Are there any visual tools to create the domain design eg. like visual paradigm exists for SSAD? 
I could not find any using google search so checking with you if any exist per your experience.

Thanks!

**Comment by kayesshu** [comment]
Hi, 

[Domain Map](http://www.domain-map.rocks/) might be relevant. Anyhow, works a check out.

Regards.

**Comment by mannion007** [comment]
Generally it's advised to keep resources from planning and modelling sessions informal so you don't get bogged down by the details of how to use a certain visual tool or make a diagram that looks appealing. People know how to use pen and paper so the full focus is on the task at hand that way. In most cases, these exercises are intended to be done collaboratively and generally pen, paper and post its with the right people in the room lend themselves much better to getting event storming, context maps and so on created efficiently. This may explain why there aren't too many tools available.

**Comment by inforeqd512** [comment]
Yes I agree somewhat... really need it for two reasons. Firstly to put down my initial thoughts on what things look like.. And once the discussion have happened, to capture it as shared document that can be collaborated upon on maintained as project documents for the devs to understand the domain.

**Comment by inforeqd512** [comment]
@kayesshu . Thank you for your suggestion. I was finally able to try that and it looks good!!. 
Will try out on more modules of the project to get some fluency.. this looks promising. 👍

**Comment by pouledodue** [comment]
"domain map" url does not work, is there a new url somewhere?

**Comment by kayesshu** [comment]
@pouledodue https://github.com/domainmap/app says it's currently "Domain Map is shutdown for now."
