### ISSUE TITLE
node.js framework

### ISSUE THREAD

**Issue by adrai** [heynickc/awesome-ddd#3]
It's possible to add http://cqrs.js.org
eventstore: https://github.com/adrai/node-eventstore
domain: https://github.com/adrai/node-cqrs-domain
denormalizer: https://github.com/adrai/node-cqrs-eventdenormalizer
saga: https://github.com/adrai/node-cqrs-saga

**Comment by heynickc** [comment]
Are the bottom 4 modules that make up the larger "cqrs.js" (your first link)?  Would you be cool with just adding that one parent project as "CQRS.js" under Frameworks and Libraries?

**Comment by adrai** [comment]
Exactly.

i.e. you can use eventstore without the rest

Add it however you like.
I'm just very happy when you add anything ?




Il giorno 2-set-2016, alle ore 19:22, Nick Chamberlain <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Are the bottom 4 modules that make up the larger "cqrs.js" (your first link)? Would you be cool with just adding that one parent project as "CQRS.js" under Frameworks and Libraries?

-

**Comment by heynickc** [comment]
Added.  Thanks!

**Comment by adrai** [comment]
thx a lot to you
