### ISSUE TITLE
DDD Document template

### ISSUE THREAD

**Issue by levalencia** [heynickc/awesome-ddd#36]
Hello

Didnt have where else to ask, but your repo has lots of information.
I am about to start a new project and want to do it with DDD, the problem is that I need to deliver a document to the customer explaining the architecture, layers, patterns, etc.

I am trying to find a DDD project documentation sample or template that I can reuse to create mine, Have you found such thing?

Thank you

**Comment by ziasistani** [comment]
I think that part of marketing in so niche that will cost the marketing departments for the required exact customized architecture and methodology documentation.
