### ISSUE TITLE
Greg Young's blog dead?

### ISSUE THREAD

**Issue by NiekGr** [heynickc/awesome-ddd#96]
I came across a few Greg Young videos, and he mentioned his blog, it is also listed on this repository. But is his blog dead? I am get a connection timeout for a few days.

And thank you for all the resources, Nick.

**Comment by witek1902** [comment]
I ping Greg on Twitter: https://twitter.com/rwitkowski_asc/status/1102507022019371009
It's probably temporary problem, we must waiting.

**Comment by witek1902** [comment]
codebetter.com works http://codebetter.com/gregyoung/
But goodenoughsoftware.net still doesn't work.

**Comment by DomenicDev** [comment]
The link provided (http://codebetter.com/gregyoung/) does not work anymore. Is there something like an official blog at the moment?
